In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
match_df = pd.read_csv(r'matches.csv',index_col=0)

In [3]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [4]:
match_df.shape

(1520, 27)

In [5]:
match_df['team'].value_counts()

Manchester City             76
Wolverhampton Wanderers     76
Burnley                     76
Leeds United                76
Everton                     76
Southampton                 76
Aston Villa                 76
Liverpool                   76
Newcastle United            76
Crystal Palace              76
Brighton and Hove Albion    76
Leicester City              76
West Ham United             76
Manchester United           76
Arsenal                     76
Tottenham Hotspur           76
Chelsea                     76
Brentford                   38
Watford                     38
Norwich City                38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Name: team, dtype: int64

In [6]:
match_df['date'] = pd.to_datetime(match_df['date'])

In [7]:
match_df.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [8]:
match_df['venue_code'] = match_df["venue"].astype("category").cat.codes

In [9]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,venue_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,0
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,1

In [10]:
match_df['opp_code'] = match_df['opponent'].astype("category").cat.codes

In [11]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0,18
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1,15
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,0,10
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,1,17

In [12]:
match_df['hour'] = match_df['time'].str.replace(":.+","",regex=True).astype("int")

In [13]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0,18,16
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1,15,15
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,12
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,0,10,15
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,1,17,15

In [14]:
match_df['day_code'] = match_df['date'].dt.dayofweek

In [15]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,16.9,1.0,0.0,0.0,2022,Manchester City,0,18,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,17.3,1.0,0.0,0.0,2022,Manchester City,1,15,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,14.0,0.0,0.0,0.0,2022,Manchester City,0,10,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,15.7,1.0,0.0,0.0,2022,Manchester City,1,17,15,5

In [16]:
match_df["target"] = (match_df['result'] == 'W').astype("int")

In [17]:
match_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0

In [18]:
# match_df['target2'] = match_df['result'].astype('category').cat.codes

In [19]:
match_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6,1

In [20]:
rf = RandomForestClassifier(n_estimators=50,min_samples_split=10,random_state=1)

## Using Last year's data to predict this year's scores

In [21]:
train = match_df[match_df['date'] < "2022-01-01"]
test = match_df[match_df['date'] > "2022-01-01"]

In [22]:
predictors = ['venue_code','opp_code','hour','day_code']

In [23]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [24]:
prediction = rf.predict(test[predictors])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy = accuracy_score(test['target'],prediction)

In [27]:
accuracy

0.6056701030927835

In [28]:
combined = pd.DataFrame(dict(actual=test['target'],predictions=prediction))

In [31]:
pd.crosstab(index=combined['actual'],columns=combined['predictions'])

predictions    0   1
actual
0            186  47
1            106  49

In [32]:
grouped_matches = match_df.groupby('team')

In [35]:
group = grouped_matches.get_group('Manchester City')

In [36]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2,0,Crystal Palace,...,1.0,0.0,0.0,2021,Manchester City,0,6,12,5,1
56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1,2,Chelsea,...,0.0,0.0,1.0,2021,Manchester City,1,5,17,5,0
57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4,3,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,0,14,20,4,1
58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2,3,Brighton,...,1.0,0.0,0.0,2021,Manchester City,0,3,19,1,0
59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5,0,Everton,...,0.0,0.0,0.0,2021,Manchester City,1,7,16,6,1

In [37]:
def rolling_average(group,cols,new_cols):
    group = group.sort_values('date')
    rolling_stats = group[cols].rolling(3,closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [38]:
cols = ['gf','ga','sh','sot','dist','fk','pk','pkatt']
new_cols = [f"{c}_rolling" for c in cols]

In [39]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [40]:
rolling_average(group,cols,new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,5,1,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,5,0,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1,0,Sheffield Utd,...,5,1,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1,1,Liverpool,...,6,0,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0,2,Tottenham,...,5,0,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4,0,Leeds United,...,5,1,3.333333,1.000000,16.000000,5.333333,16.700000,0.333333,0.333333,0.333333
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5,0,Newcastle Utd,...,6,1,4.000000,0.333333,18.666667,6.000000,16.333333,0.000000,0.333333,0.333333
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5,1,Wolves,...,2,1,4.666667,0.333333,20.000000,7.333333,15.166667,0.333333,0.333333,0.333333
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,West Ham,...,6,0,4.666667,0.333333,18.333333,6.666667,14.933333,0.333333,0.000000,0.000000
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,Aston Villa,...,6,1,4.000000,1.000000,22.000000,7.000000,15.700000,1.000000,0.000000,0.333333

In [41]:
match_rolling = match_df.groupby('team').apply(lambda x: rolling_average(x,cols,new_cols))

In [42]:
match_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 37 2022-04-30  15:00  Premier League  Matchweek 35
                        38 2022-05-07  15:00  Premier League  Matchweek 36
                        39 2022-05-11  20:15  Premier League  Matchweek 33
                        40 2022-05-15  14:00  Premier League  Matchweek 37
                        41 2022-05-22  16:00  Premier League  Matchweek 38

                            day venue result  gf  ga         opponent  ...  \
team                                                                   ...
Arsenal                 6   Sun  Home      W   2   1    Sheffield Utd  ...
                        7   Sat  Away      L   0   1  Manchester City  ...
                        9   Sun  Home      L   0   1   Leicester City  ...
                        11  Sun  Away      W   1   0   Manchester Utd  ...
                        13  Sun  Home      L   0   3      Aston Villa  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 37  Sat  Home      L   0   3         Brighton  ...
                        38  Sat  Away      D   2   2          Chelsea  ...
                        39  Wed  Home      L   1   5  Manchester City  ...
                        40  Sun  Home      D   1   1     Norwich City  ...
                        41  Sun  Away      L   1   3        Liverpool  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 6          6       1    2.000000    1.333333
                        7          5       0    1.666667    1.666667
                        9          6       0    1.000000    1.666667
                        11         6       1    0.666667    1.000000
                        13         6       0    0.333333    0.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 37         5       0    0.666667    1.000000
                        38         5       0    0.000000    1.666667
                        39         2       0    0.666667    2.000000
                        40         6       0    1.000000    3.333333
                        41         6       0    1.333333    2.666667

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 6    7.666667    3.666667    14.733333   0.666667
                        7    5.333333    3.666667    15.766667   0.000000
                        9    7.000000    3.666667    16.733333   0.666667
                        11   9.666667    4.000000    16.033333   1.000000
                        13   9.666667    2.666667    18.033333   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 37   8.666667    3.333333    16.966667   0.000000
                        38   8.666667    2.333333    18.233333   0.333333
                        39  11.666667    3.000000    17.133333   0.333333
                        40  10.666667    2.666667    16.400000   0.333333
                        41  12.666667    3.666667    17.033333   0.666667

                            pk_rolling  pkatt_rolling
team
Arsenal                 6     0.000000       0.000000
                        7     0.000000       0.000000
                        9     0.000000       0.000000
                        11    0.000000       0.000000
                        13    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 37    0.000000       0.000000
                        38    0.000000       0.000000
                        39    0.000000       0.000000
                        40    0.000000       0.000000
                        41    0.000000       0.000000

[1448 rows x 40 columns]

In [43]:
match_rolling = match_rolling.droplevel('team')

In [44]:
match_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Home,L,0,3,Brighton,...,5,0,0.666667,1.000000,8.666667,3.333333,16.966667,0.000000,0.000000,0.000000
38,2022-05-07,15:00,Premier League,Matchweek 36,Sat,Away,D,2,2,Chelsea,...,5,0,0.000000,1.666667,8.666667,2.333333,18.233333,0.333333,0.000000,0.000000
39,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,2,0,0.666667,2.000000,11.666667,3.000000,17.133333,0.333333,0.000000,0.000000
40,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,6,0,1.000000,3.333333,10.666667,2.666667,16.400000,0.333333,0.000000,0.000000
41,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,6,0,1.333333,2.666667,12.666667,3.666667,17.033333,0.666667,0.000000,0.000000

In [45]:
match_rolling.index = range(match_rolling.shape[0])

In [46]:
match_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Home,L,0,3,Brighton,...,5,0,0.666667,1.000000,8.666667,3.333333,16.966667,0.000000,0.000000,0.000000
1444,2022-05-07,15:00,Premier League,Matchweek 36,Sat,Away,D,2,2,Chelsea,...,5,0,0.000000,1.666667,8.666667,2.333333,18.233333,0.333333,0.000000,0.000000
1445,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,2,0,0.666667,2.000000,11.666667,3.000000,17.133333,0.333333,0.000000,0.000000
1446,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,6,0,1.000000,3.333333,10.666667,2.666667,16.400000,0.333333,0.000000,0.000000
1447,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,6,0,1.333333,2.666667,12.666667,3.666667,17.033333,0.666667,0.000000,0.000000

In [48]:
from sklearn.metrics import precision_score

In [51]:
def makepredictions(data,predictors):
    train = data[data['date'] < "2022-01-01"]
    test = data[data['date'] > "2022-01-01"]
    rf.fit(train[predictors], train["target"])
    prediction = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['target'],predictions=prediction))
    precision = precision_score(test['target'],prediction)
    return combined,precision

In [52]:
combined, precision = makepredictions(match_rolling,predictors+new_cols)

In [53]:
precision

0.6027397260273972

In [55]:
pd.crosstab(index=combined['actual'],columns=combined['predictions'])

predictions    0   1
actual
0            204  29
1            111  44

In [56]:
combined = combined.merge(match_rolling[['date','team','opponent','result']] , left_index = True,right_index=True)

In [57]:
combined

,actual,predictions,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,1,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L

In [59]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values = {
    'Brighton and Hove Albion':'Brighton',
    'Manchester United':'Manchester Utd',
    'Newcastle United': 'Newcastle Utd',
    'Tottenham Hotsput': 'Tottenham',
    'West Ham United': 'West Ham',
    'Wolverhampton Wanderers':'Wolves'
}

mapping = MissingDict(**map_values)

In [60]:
mapping['West Ham United']

'West Ham'

In [61]:
combined['new_team'] = combined['team'].map(mapping)

In [62]:
combined

,actual,predictions,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves

In [63]:
merged = combined.merge(combined,left_on=['date','new_team'],right_on=['date','opponent'])

In [64]:
merged

,actual_x,predictions_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predictions_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves,1,0,Brighton and Hove Albion,Wolves,W,Brighton
364,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves,0,0,Chelsea,Wolves,D,Chelsea
365,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City
366,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves,0,0,Norwich City,Wolves,D,Norwich City
367,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool

In [66]:
merged[(merged['predictions_x'] == 1) & (merged['predictions_y'] == 0)]['actual_x'].value_counts()

1    38
0    26
Name: actual_x, dtype: int64

In [68]:
38/(38+26)

0.59375